
cc_binary(
    name = "greeter_server",
    srcs = ["greeter_server.cpp"],
    deps = [
        ":cppGamConcensusGrpclib",
    ],
)

cc_binary(
    name = "greeter_client",
    srcs = ["greeter_client.cpp"],
    deps = [
        ":cppGamConcensusGrpclib",
    ],
)